# Generated by Django 6.1.1 on 2026-09-21 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=200)),
                ('movie_actor', models.CharField(max_length=200)),
                ('movie_general', models.CharField(max_length=300)),
                ('movie_VJ', models.CharField(max_length=200)),
                ('movie_cost', models.CharField(max_length=300)),
                ('movie_status1', models.CharField(choices=[('New', 'New'), ('Featured', 'Featured')], default='New', max_length=300)),
                ('movie_status2', models.CharField(choices=[('Free', 'Free'), ('Paid', 'Paid')], max_length=200)),
                ('movie_release_date', models.DateField(auto_now_add=True)),
                ('movie_image', models.ImageField(upload_to='pic')),
                ('movie_video', models.FileField(upload_to='m_videos')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_name', models.CharField(max_length=200)),
                ('release_date', models.DateField()),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie_title', models.CharField(max_length=200)),
                ('serie_actor', models.CharField(max_length=200)),
                ('serie_general', models.CharField(max_length=300)),
                ('serie_VJ', models.CharField(max_length=200)),
                ('serie_cost', models.CharField(max_length=200)),
                ('serie_status1', models.CharField(choices=[('New', 'New'), ('Featured', 'Featured')], max_length=300)),
                ('serie_status2', models.CharField(choices=[('Free', 'Free'), ('Paid', 'Paid')], max_length=200)),
                ('serie_release_date', models.DateField(auto_now_add=True)),
                ('serie_image', models.ImageField(upload_to='pic')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_name', models.CharField(max_length=200)),
                ('release_date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('episode_video', models.FileField(upload_to='s_videos')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieafrican.season')),
            ],
        ),
        migrations.AddField(
            model_name='season',
            name='serie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieafrican.series'),
        ),
    ]
